spring:
  application:
    name: "core-module"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/restaurant
    username: postgres
    password: shalin123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    user: postgres
    password: shalin123
    baseline-version: 0
    baseline-description: "initial"
server:
  port: 8080
  servlet:
    context-path: /restaurant/core
logging:
  level:
    com.iamnirvan.restaurant.core: DEBUG